name: dakshilipy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter>=1.0.0
  - pandas>=1.4.4
  - python=3.9.13
  - pip>=22.2.2
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - plotly>=5.0.0
  - ipywidgets>=8.0.0
  - pip:
    - ideas>=0.1.3
    - token-utils>=0.1.8
    - k3d>=2.15.0
